package rando

var (
	adv = []string{
		"a dreadfully",
		"a filthy",
		"a horribly",
		"a preposterously",
		"a ridiculously",
		"a woefully",
		"an absurdly",
		"an indescribably",
		"an inexcusably",
		"an irredeemably",
		"an offensively",
		"an outrageously",
		"an unholy",
	}

	adj = []string{
		"annoying",
		"appalling",
		"asinine",
		"atrocious",
		"bitchass",
		"bitter",
		"cantankerous",
		"cretinous",
		"cynical",
		"decrepit",
		"dense",
		"depraved",
		"deplorable",
		"despicable",
		"disgusting",
		"dysfunctional",
		"grotesque",
		"hermaphroditic",
		"hopeless",
		"ignorant",
		"illiterate",
		"inbred",
		"incompetent",
		"inept",
		"insignificant",
		"insufferable",
		"intolerable",
		"irresponsible",
		"miserable",
		"mundane",
		"naive",
		"narcissistic",
		"nasty",
		"nauseating",
		"obnoxious",
		"parasitic",
		"pedestrian",
		"perverted",
		"petty",
		"pompous",
		"reprehensible",
		"repulsive",
		"sinister",
		"skanky",
		"slutty",
		"spastic",
		"superficial",
		"syphilitic",
		"toxic",
		"uncivilized",
		"unkempt",
		"vile",
		"worthless",
	}

	noun = []string{
		"ballsack",
		"bastard",
		"bitch",
		"chicken-diddler",
		"chode",
		"chodemuffin",
		"cockholster",
		"cockjockey",
		"cocksucker",
		"cuck",
		"cumbubble",
		"cumdumpster",
		"cumjunkie",
		"cuntpuddle",
		"dickhead",
		"dickhole",
		"dickwad",
		"dipshit",
		"douchebag",
		"dumbass",
		"dumpsterslut",
		"faggot",
		"fuckface",
		"fucknugget",
		"fuckstick",
		"fucktard",
		"fuckwad",
		"fuckwit",
		"gutterslut",
		"jackass",
		"jizzmonger",
		"jizzmuffin",
		"lardass",
		"meatflap",
		"parasite",
		"peasant",
		"pervert",
		"piece of shit",
		"piece of garbage",
		"pleb",
		"prick",
		"pussy",
		"queef",
		"retard",
		"sack of shit",
		"schlong",
		"scrotum",
		"shitbird",
		"shithead",
		"shitpouch",
		"shitstain",
		"shitter",
		"skank",
		"slut",
		"spermatorium",
		"sphincter",
		"splooge-vacuum",
		"swine",
		"taint",
		"thundercunt",
		"turdburglar",
		"twat",
		"whore",
	}

	desc = []string{
		"alabama-hot-pocket-loving",
		"bed-wetting",
		"blue-waffle-loving",
		"bug-eyed",
		"chromosome-deficient",
		"cockeyed",
		"cock-juggling",
		"cocksucking",
		"corpse-fucking",
		"cum-guzzling",
		"dick-infested",
		"dildo-munching",
		"dirty-sanchez-wearing",
		"disease-ridden",
		"drug-addled",
		"enema-addicted",
		"feebleminded",
		"finger-banging",
		"fudge-packing",
		"glass-bottom-boat-loving",
		"horse-fucking",
		"irredeemably-boring",
		"kid-diddling",
		"orgasm-faking",
		"pig-fucking",
		"piss-drinking",
		"poon-guzzling",
		"raging",
		"sheep-fucking",
		"shit-eating",
		"simple-minded",
		"small-minded",
		"soul-destroying",
	}

	finisher = []string{
		"cesspool of sub-human filth",
		"evangelical crusader of sub-mediocrity",
		"failure whose existence is meaningless and will be forgotten by everyone",
		"molester of small furry animals",
		"plotless melodrama of an uneventful life",
		"poster child for birth control",
		"practitioner of nonconsentual bestiality",
		"<noun> who should go play in traffic",
		"<noun> whose a bigger disappointment than fucking Pluto",
		"<noun> whose birth certificate is an apology from the condom factory",
		"<noun> whose life will never amount to anything",
		"<noun> whose mother should have swallowed",
		"<noun> whose never had a conversation with anyone where the other person wasn't just shaking their head in disappointment",
		"<noun> with delusions of adequacy",
		"<noun> with the natural grace of a drunken panda suffering from vertigo",
	}

	youNoFuckMe = `What the fuck did you just fucking type about my homie, you little bitch?

I’ll have you know I graduated top of my class at MIT, and I’ve been involved in numerous secret raids with Anonymous, and I have over 300 confirmed DDoSes.
I am trained in online trolling and I’m the top hacker in the entire world. You are nothing to me but just another virus host.
I will wipe you the fuck out, with precision the likes of which has never been seen before on the Internet. Mark my fucking words.

You think you can get away with typing that shit about my friend over the Internet? Think again, fucker.

As we chat over IRC I am tracing your IP with my damn bare hands.
So you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your computer.
You’re fucking dead, kid.

I can be anywhere, anytime, and I can hack into your files in over seven hundred ways, and that’s just with my bare hands.
Not only am I extensively trained in hacking but I have access to the entire arsenal of every piece of malware ever created, and I will use it to its full extent to wipe your miserable ass off the face of the world wide web, you little shit.

If only you could have known what unholy retribution your "clever" little comment was about to bring down upon you, maybe you would have held your fucking fingers.
But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot.

I will shit code all over you and you will drown in it. You’re fucking dead, kiddo.`

	cleanAdj = []string{
		"angry",
		"banana",
		"beech",
		"beef",
		"bizarre",
		"blue",
		"bookish",
		"chilly",
		"durable",
		"egregious",
		"extra",
		"green",
		"happy",
		"hopping",
		"irate",
		"junior",
		"latent",
		"loud",
		"odd",
		"orange",
		"peeved",
		"red",
		"silent",
		"sleepy",
		"slimy",
		"somber",
		"sticky",
		"strange",
		"united",
		"violent",
		"violet",
		"weird",
		"wobbly",
		"wrong",
		"yellow",
	}

	cleanNoun = []string{
		"ark",
		"artist",
		"auto",
		"bagel",
		"beam",
		"blunder",
		"bounce",
		"calendar",
		"chaser",
		"chef",
		"chipmunk",
		"curtain",
		"deity",
		"entourage",
		"farm",
		"feed",
		"felony",
		"fire",
		"genesis",
		"glee",
		"gopher",
		"iron",
		"llama",
		"master",
		"monkey",
		"monkey",
		"montana",
		"moon",
		"napkin",
		"net",
		"night",
		"panda",
		"penguin",
		"photo",
		"plow",
		"rage",
		"route",
		"scan",
		"seagull",
		"set",
		"source",
		"spatula",
		"spawn",
		"spork",
		"squirrel",
		"sucker",
		"toll",
		"tote",
		"trawl",
		"trinity",
		"trough",
		"waffle",
		"walk",
		"watch",
		"water",
		"whisper",
		"yard",
		"zipper",
	}
)
